### ISSUE TITLE
Problem with simple testcase

### ISSUE THREAD

**Issue by silvio** [mtdowling/jmespath.rs#16]
Hi,

is this project still active?
I have a wrong behaviour with the (compliance) test cases. I don't know what is going wrong, but something bad happen here.

I added two test cases like this one:

``` diff
diff --git a/tests/compliance/basic.json b/tests/compliance/basic.json
index d550e96..38b41db 100644
--- a/tests/compliance/basic.json
+++ b/tests/compliance/basic.json
@@ -92,5 +92,20 @@
             "result": "bar"
          }
     ]
+},
+{
+    "given": {"a": true},
+    "cases": [
+        {
+            "comment": "simple basic test true",
+            "expression": "a",
+            "result": true
+        },
+        {
+            "comment": "simple basic test false",
+            "expression": "a",
+            "result": false
+        }
+    ]
 }
 ]
```

I get this result:

``` plain
test test_basic_0_0_simple_basic_test_true ... ok
test test_basic_0_1_simple_basic_test_false ... ok
```

My expectation was that one of this tests should fail. I'm wrong?

Some investigation: The characteristic of the problem is that  `Assertion::assert` returns with an `Ok(())` because `r.as_string()` returns a `None`. The function `as_string()` returns only a string object if the `Variable` is a `String` typed value. (doc/src/jmespath/variable.rs.html#170-175)

**Comment by mtdowling** [comment]
I *think* this is due to the test case code generation. Because the expression is the same for both test cases with the same data, the generate function is the same. We'd need to also include the test case number in the generated method name to work around edge cases like this.

**Comment by mtdowling** [comment]
There was a bug in the test runner where things other than strings weren't actually being compared. There were also a number of bugs in the parser. Bother have been fixed in master.
